ALTER TABLE user ALTER COLUMN username VARCHAR(30);
ALTER TABLE user ALTER COLUMN password VARCHAR(30);
ALTER TABLE user ALTER COLUMN first_name VARCHAR(50);
ALTER TABLE user ALTER COLUMN last_name VARCHAR(50);